### ISSUE TITLE
Questions about ex-RHCR

### ISSUE THREAD

**Issue by zhx0506** [NitzanMadar/exPBS-exRHCR#2]
Thank you for your reply. I tested the method on a warehouse map using Python with the script “L-MAPF/run_windowed_L-MAPF_test_kiva_warehouse.py.” The main parameter configuration followed the recommendations from the paper: [-a 128 -c 1 -d 1 -t 10 -l 10 (the width limit parameter for WL-DFS) -r 5 -p 2], with the number of agents set to 128.  total_step_limit = 500. After verification, I found that the task assignment of EX-RHCR in the warehouse was consistent with that of RHCR. Based on the test results shown below, I would like to confirm whether this indicates that we are using EX-RHCR correctly?
![5b76ee81c4fb07c28d76dc5a517f712](https://github.com/user-attachments/assets/67f7d9c6-92e0-45f0-ad17-d5c055746641)

**Comment by NitzanMadar** [comment]
This is a partial screenshot, but as far as I remember, it looks fine.
I see you did not use an existing `.agents` file, I assume it was automatically created since you use 128 agents.
I'll be happy to hear your research directions and share some thoughts that may assist you.

**Comment by zhx0506** [comment]
Thank you for your response. We plan to use EX-RHCR as a comparison method and have two questions:


If the existing agents file does not include the number of agents to be evaluated, will automatically generating the agents file affect the results?



If I need to evaluate other maps, is it feasible to directly modify the map file and the new_mission_list?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NitzanMadar/exPBS-exRHCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月15日(星期二) 下午2:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NitzanMadar/exPBS-exRHCR] Questions about ex-RHCR (Issue #2)





 
This is a partial screenshot, but as far as I remember, it looks fine.
 I see you did not use an existing .agents file, I assume it was automatically created since you use 128 agents.
 I'll be happy to hear your research directions and share some thoughts that may assist you.
